server:
  port: 9001

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:billing_integration_mock;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true